name: UI Test
on:
 push:
  branches:
    - feature/github-actions-ecommerce
jobs: 
  ui-tests:

    runs-on: ubuntu-latest
    strategy:
      matrix:
       include:
         - os: ubuntu-latest
           node: 14
           test: product-listing-page.test.js
         - os: ubuntu-latest
           node: 14
           test: product-details-page.test.js
         - os: ubuntu-latest
           node: 14
           test: shopping-cart-functionality.test.js
         - os: ubuntu-latest
           node: 14
           test: payment-gateway-integration.test.js
    steps:
      - name: Use Node.js
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test $
