name: OWASP ZAP Baseline Scan

on:
  push:
    branches:
      - feature-branch-name
  pull_request:

jobs:
  zap-baseline-scan:
    name: OWASP ZAP Baseline Scan
    runs-on: ubuntu-latest
    
    steps:
      # Checkout the code from the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Run the ZAP baseline scan
      - name: OWASP ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.7.0
        with:
          # Specify the target URL for the scan
          target: 'https://juice-shop.herokuapp.com/#'
          # Set fail on failure to true (default), but you can customize it
          cmd_options: '-t 60 -r zap_report.html'
        
      # Upload the ZAP report as an artifact
      - name: Upload ZAP Scan Report
        uses: actions/upload-artifact@v3
        with:
          name: zap-report
          path: zap_report.html
